#!/usr/bin/env bash
# ==============================================================================
# MAILUTILS-SETUP - Configure mail sending through Proton Mail Bridge
# ==============================================================================
# Description: Sets up /etc/mail.rc and /etc/ssmtp/ssmtp.conf for email testing
# Version: 1.0.0
# ==============================================================================

setup_dir() {
    local DIR="$1"
    echo "DIR: $1"
    mkdir -p "${DIR}"
    chown -R "${PUID}:${PGID}" "${DIR}"
    chmod 700 "${DIR}"
}

return_message() {
    echo "Returning to entrypoint..."
    sleep 2
    echo "....................................................................."
    echo "....................................................................."
}

echo "-------------------------MAILUTILS SETUP-----------------------------"
echo "Setting up mailutils for outgoing mail..."
echo "---"
echo "NOTE:"
echo "Please check that PROTON_BRIDGE_PASSWORD matches the one generated"
echo "by Proton Mail Bridge. Alternatively, set PROTON_BRIDGE_PASSWORD_FILE"
echo "as an absolute path to the file holding the password (e.g. for Docker secrets)."
echo "Use proton-bridge --cli to run the 'info' command to check your password."
echo "---"
echo ""
sleep 1

# Get the bridge password from the file or env var
if [ -n "${PROTON_BRIDGE_PASSWORD_FILE:+1}" ]; then
    echo "PROTON_BRIDGE_PASSWORD_FILE set. Following path to vault password file."
    if [ -f "${PROTON_BRIDGE_PASSWORD_FILE}" ]; then
        SMTP_AUTH_PASSWORD="$(cat "${PROTON_BRIDGE_PASSWORD_FILE}")"
        echo "Successfully read password from file."
    else
        echo "---"
        echo "WARNING: PROTON_BRIDGE_PASSWORD_FILE points to non-existent file: ${PROTON_BRIDGE_PASSWORD_FILE}"
        echo "         Will try PROTON_BRIDGE_PASSWORD environment variable instead."
        echo "---"
        SMTP_AUTH_PASSWORD="${PROTON_BRIDGE_PASSWORD}"
    fi
else
    if [ -n "${PROTON_BRIDGE_PASSWORD:+1}" ]; then
        echo "PROTON_BRIDGE_PASSWORD set. Using provided vault password."
        SMTP_AUTH_PASSWORD="${PROTON_BRIDGE_PASSWORD}"
    else
        echo "---"
        echo "WARNING: Neither PROTON_BRIDGE_PASSWORD nor PROTON_BRIDGE_PASSWORD_FILE are set."
        echo "         smtp-auth-password will be set to default value, PASSWORD_NOT_YET_SET."
        echo "         Please set PROTON_BRIDGE_PASSWORD or PROTON_BRIDGE_PASSWORD_FILE to the"
        echo "         password generated by Proton Bridge."
        echo "         Use 'proton-bridge --cli' and the 'info' command to view it."
        echo "---"
        SMTP_AUTH_PASSWORD='PASSWORD_NOT_YET_SET'
    fi
fi

############################## /ETC/MAIL.RC ##############################
echo "Configuring /etc/mail.rc for the mail command..."
sleep 1

cat > /etc/mail.rc << EOF
# Mail configuration for Proton Mail Bridge
set smtp=smtp://localhost:${SMTP_INSIDE_PORT}
set smtp-auth=login
set smtp-auth-user="${PROTON_EMAIL}"
set smtp-auth-password="${SMTP_AUTH_PASSWORD}"
set ssl-verify=ignore
set nss-config-dir=/etc/pki/nssdb/
# Set default From address
set from="${PROTON_EMAIL}"
# Always show delivery details
set verbose
EOF

MAIL_RC_RETURN=$?
if [ $MAIL_RC_RETURN -ne 0 ]; then
    echo "ERROR: /etc/mail.rc configuration failed with exit code ${MAIL_RC_RETURN}"
    exit 1
else
    echo "/etc/mail.rc successfully configured."
fi

echo "mail.rc contents (password hidden):"
sed 's/'"${SMTP_AUTH_PASSWORD}"'/******/g' < /etc/mail.rc
sleep 1

######################### /ETC/SSMTP/SSMTP.CONF ##########################
echo "Configuring /etc/ssmtp/ssmtp.conf for the ssmtp command..."
sleep 1

cat > /etc/ssmtp/ssmtp.conf << EOF
# SSMTP configuration for Proton Mail Bridge
# The person who gets all mail for userids < 1000
root=${PROTON_EMAIL}

# The mail server (where the mail is sent to)
mailhub=127.0.0.1:${SMTP_INSIDE_PORT}

# The domain name to use in outgoing mail
rewriteDomain=${DOMAIN}

# The full hostname
hostname=mail.${DOMAIN}

# Are users allowed to set their own From: address?
# YES - Allow the user to specify their own From: address
# NO - Use the system generated From: address
FromLineOverride=YES

# Authentication to the Bridge (if needed)
AuthUser=${PROTON_EMAIL}
AuthPass=${SMTP_AUTH_PASSWORD}
EOF

SSMTP_CONF_RETURN=$?
if [ $SSMTP_CONF_RETURN -ne 0 ]; then
    echo "ERROR: /etc/ssmtp/ssmtp.conf configuration failed with exit code ${SSMTP_CONF_RETURN}"
    exit 1
else
    echo "/etc/ssmtp/ssmtp.conf successfully configured."
fi

echo "ssmtp.conf contents (password hidden):"
sed 's/AuthPass=.*/AuthPass=******/g' < /etc/ssmtp/ssmtp.conf
sleep 1

##########################################################################
echo "mailutils setup complete."
return_message
